<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="VinylPi" duration-ms="7102" started-at="2016-04-24T20:51:17Z" finished-at="2016-04-24T20:51:24Z">
    <groups>
    </groups>
    <test name="Regression1" duration-ms="7102" started-at="2016-04-24T20:51:17Z" finished-at="2016-04-24T20:51:24Z">
      <class name="org.vinylpi.tests.unittests.StatPageTest">
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String)[pri:0, instance:org.vinylpi.tests.unittests.StatPageTest@a52a72a]" name="beforeClass" is-config="true" duration-ms="6501" started-at="2016-04-24T16:51:17Z" finished-at="2016-04-24T16:51:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://192.168.1.131:8090/stat.html]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ffserver Status]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testConnectionAvailable(java.lang.String, java.lang.String)[pri:0, instance:org.vinylpi.tests.unittests.StatPageTest@a52a72a]" name="testConnectionAvailable" duration-ms="29" started-at="2016-04-24T16:51:23Z" finished-at="2016-04-24T16:51:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[pi-feed.ffm(input)]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[connectinon-name]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Connection not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Connection not available expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.vinylpi.tests.unittests.StatPageTest.testConnectionAvailable(StatPageTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testConnectionAvailable -->
        <test-method status="FAIL" signature="testStreamAvailable(java.lang.String, java.lang.String)[pri:0, instance:org.vinylpi.tests.unittests.StatPageTest@a52a72a]" name="testStreamAvailable" duration-ms="32" started-at="2016-04-24T16:51:23Z" finished-at="2016-04-24T16:51:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[pi-stream.mp3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[stream-path]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Stream not available expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Stream not available expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.vinylpi.tests.unittests.StatPageTest.testStreamAvailable(StatPageTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStreamAvailable -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:org.vinylpi.tests.unittests.StatPageTest@a52a72a]" name="afterClass" is-config="true" duration-ms="523" started-at="2016-04-24T16:51:23Z" finished-at="2016-04-24T16:51:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- org.vinylpi.tests.unittests.StatPageTest -->
    </test> <!-- Regression1 -->
  </suite> <!-- VinylPi -->
</testng-results>
